
import { Clinic } from './types';

export const CLINICS: Clinic[] = [
  // WESTERN AREA URBAN (Freetown)
  {
    id: '1',
    name: 'Connaught Hospital',
    location: 'Percival Street, Freetown',
    district: 'Western Area Urban',
    phone: '+232 76 610000',
    type: 'Government Referral Hospital',
    is24Hour: true,
    isAddictionSupport: false,
    lat: 8.487,
    lng: -13.235,
    description: 'The main national referral hospital for surgical and complex medical emergencies. Established in 1912.'
  },
  {
    id: '2',
    name: 'PCMH (Princess Christian Maternity Hospital)',
    location: 'Fourah Bay Road, Freetown',
    district: 'Western Area Urban',
    phone: '+232 22 223101',
    type: 'Maternity Hospital',
    is24Hour: true,
    isAddictionSupport: false,
    lat: 8.489,
    lng: -13.220,
    description: 'Specialized maternity and obstetric care for women and newborns. Commonly known as Cottage Hospital.'
  },
  {
    id: '3',
    name: 'Ola During Children’s Hospital',
    location: 'Fourah Bay Road, Freetown',
    district: 'Western Area Urban',
    phone: '+232 22 223101',
    type: 'Children’s Hospital',
    is24Hour: true,
    isAddictionSupport: false,
    lat: 8.489,
    lng: -13.221,
    description: 'The national pediatric referral center, offering specialized care for infants and children up to age 12.'
  },
  {
    id: '8',
    name: 'Sierra Leone Psychiatric Hospital',
    location: 'Kissy, Freetown',
    district: 'Western Area Urban',
    phone: '+232 77 000117',
    type: 'Mental Health Facility',
    is24Hour: true,
    isAddictionSupport: true,
    lat: 8.473,
    lng: -13.197,
    description: 'Primary mental health and psychiatric rehabilitation center. Recently renovated with modern wards.'
  },
  {
    id: '9',
    name: '34 Military Hospital',
    location: 'Wilberforce, Freetown',
    district: 'Western Area Urban',
    phone: '+232 76 000034',
    type: 'Military Hospital',
    is24Hour: true,
    isAddictionSupport: false,
    lat: 8.468,
    lng: -13.272,
    description: 'Serving military personnel and civilians. Known for high standards of hygiene and efficient emergency response.'
  },
  {
    id: '11',
    name: 'Blue Shield Pharmacy',
    location: 'Siaka Stevens Street, Freetown',
    district: 'Western Area Urban',
    phone: '+232 76 543210',
    type: 'Pharmacy',
    is24Hour: false,
    isAddictionSupport: false,
    lat: 8.484,
    lng: -13.234,
    description: 'Central Freetown pharmacy providing a wide range of essential medications and health consultation.'
  },

  // WESTERN AREA RURAL
  {
    id: '7',
    name: 'City of Rest Rehabilitation Centre',
    location: 'Grafton, Freetown',
    district: 'Western Area Rural',
    phone: '+232 76 612345',
    type: 'Addiction & Mental Health Centre',
    is24Hour: true,
    isAddictionSupport: true,
    lat: 8.411,
    lng: -13.146,
    description: 'Specialized center for drug addiction recovery, mental health counseling, and spiritual support for youth.'
  },
  {
    id: '12',
    name: 'Waterloo Health Centre',
    location: 'Main Road, Waterloo',
    district: 'Western Area Rural',
    phone: '+232 79 000123',
    type: 'Government Health Centre',
    is24Hour: true,
    isAddictionSupport: false,
    lat: 8.338,
    lng: -13.070,
    description: 'Serving the growing population of Waterloo and surrounding villages with primary healthcare.'
  },

  // NORTHERN PROVINCE (Bombali, Tonkolili, Koinadugu, Falaba)
  {
    id: '6',
    name: 'Makeni Regional Hospital',
    location: 'Hospital Road, Makeni',
    district: 'Bombali',
    phone: '+232 52 250201',
    type: 'Government Regional Hospital',
    is24Hour: true,
    isAddictionSupport: false,
    lat: 8.883,
    lng: -12.045,
    description: 'The largest hospital in the North, serving as a hub for Bombali and neighboring districts.'
  },
  {
    id: '28',
    name: 'Holy Spirit Hospital Makeni',
    location: 'Masuba, Makeni',
    district: 'Bombali',
    phone: '+232 76 625141',
    type: 'Mission Hospital',
    is24Hour: true,
    isAddictionSupport: false,
    lat: 8.881,
    lng: -12.052,
    description: 'Private mission hospital highly regarded for specialized surgery and outpatient diagnostic services.'
  },
  {
    id: '24',
    name: 'UCC Pharmacy Makeni',
    location: 'Azzolini Highway, Makeni',
    district: 'Bombali',
    phone: '+232 76 123456',
    type: 'Pharmacy',
    is24Hour: false,
    isAddictionSupport: false,
    lat: 8.885,
    lng: -12.048,
    description: 'Reliable supplier of prescription drugs and general health supplies in central Makeni.'
  },
  {
    id: '14',
    name: 'Magburaka Government Hospital',
    location: 'Magburaka Town',
    district: 'Tonkolili',
    phone: '+232 78 444555',
    type: 'Government District Hospital',
    is24Hour: true,
    isAddictionSupport: false,
    lat: 8.715,
    lng: -11.946,
    description: 'Primary public hospital for Tonkolili district, recently updated with a specialized oxygen plant.'
  },
  {
    id: '23',
    name: 'Masanga Hospital',
    location: 'Masanga, near Magburaka',
    district: 'Tonkolili',
    phone: '+232 79 123789',
    type: 'Referral Hospital',
    is24Hour: true,
    isAddictionSupport: false,
    lat: 8.746,
    lng: -11.835,
    description: 'Specialized surgical and rehabilitation center known for its work with orthopedic patients.'
  },
  {
    id: '15',
    name: 'Kabala Government Hospital',
    location: 'Kabala Town',
    district: 'Koinadugu',
    phone: '+232 76 111222',
    type: 'Government District Hospital',
    is24Hour: true,
    isAddictionSupport: false,
    lat: 9.587,
    lng: -11.552,
    description: 'Serving the mountainous Koinadugu district with emergency and surgical facilities.'
  },
  {
    id: '50',
    name: 'Fadugu Community Health Centre',
    location: 'Fadugu Town',
    district: 'Koinadugu',
    phone: '+232 76 234876',
    type: 'Government Health Facility',
    is24Hour: true,
    isAddictionSupport: false,
    lat: 9.387,
    lng: -11.752,
    description: 'Provides essential primary care and maternal services for the Fadugu community.'
  },
  {
    id: '51',
    name: 'Alkalia Health Centre',
    location: 'Alkalia',
    district: 'Koinadugu',
    phone: '+232 76 345765',
    type: 'Government Health Facility',
    is24Hour: true,
    isAddictionSupport: false,
    lat: 9.215,
    lng: -11.512,
    description: 'Rural health post serving remote villages in the Southern Koinadugu area.'
  },
  {
    id: '52',
    name: 'Kabala Star Pharmacy',
    location: 'Kabala Central',
    district: 'Koinadugu',
    phone: '+232 76 456654',
    type: 'Pharmacy',
    is24Hour: false,
    isAddictionSupport: false,
    lat: 9.585,
    lng: -11.554,
    description: 'Leading medicine supplier in Kabala town with professional pharmacist consultation.'
  },

  // NORTHWEST PROVINCE (Port Loko, Kambia, Karene)
  {
    id: '13',
    name: 'St. John of God Catholic Hospital',
    location: 'Lunsar, Marampa',
    district: 'Port Loko',
    phone: '+232 76 602354',
    type: 'Mission Hospital',
    is24Hour: true,
    isAddictionSupport: false,
    lat: 8.685,
    lng: -12.535,
    description: 'A major surgical referral center in Lunsar, famous for its high-quality ophthalmic (eye) surgery.'
  },
  {
    id: '10',
    name: 'Lungi Government Hospital',
    location: 'Lungi Town',
    district: 'Port Loko',
    phone: '+232 78 123456',
    type: 'Government District Hospital',
    is24Hour: true,
    isAddictionSupport: false,
    lat: 8.621,
    lng: -13.201,
    description: 'Serving Lungi and travelers, including emergency medical services for airport transit.'
  },
  {
    id: '16',
    name: 'Port Loko Government Hospital',
    location: 'Port Loko Town',
    district: 'Port Loko',
    phone: '+232 76 987654',
    type: 'Government District Hospital',
    is24Hour: true,
    isAddictionSupport: false,
    lat: 8.766,
    lng: -12.788,
    description: 'The main referral hospital for Port Loko district, specializing in pediatric and maternal health.'
  },
  {
    id: '27',
    name: 'Lunsar Pharmacy',
    location: 'Main Road, Lunsar',
    district: 'Port Loko',
    phone: '+232 77 999888',
    type: 'Pharmacy',
    is24Hour: false,
    isAddictionSupport: false,
    lat: 8.687,
    lng: -12.533,
    description: 'Central medicine store for Lunsar town and neighboring mining communities.'
  },
  {
    id: '17',
    name: 'Kambia Government Hospital',
    location: 'Kambia Town',
    district: 'Kambia',
    phone: '+232 76 555666',
    type: 'Government District Hospital',
    is24Hour: true,
    isAddictionSupport: false,
    lat: 9.125,
    lng: -12.921,
    description: 'Vital facility near the border, handling both local and cross-border health emergencies.'
  },

  // EASTERN PROVINCE (Kenema, Kono, Kailahun)
  {
    id: '5',
    name: 'Kenema Government Hospital',
    location: 'Combema Road, Kenema',
    district: 'Kenema',
    phone: '+232 42 220201',
    type: 'Government Regional Hospital',
    is24Hour: true,
    isAddictionSupport: false,
    lat: 7.874,
    lng: -11.185,
    description: 'Regional hospital for the East. Known globally for its Lassa Fever and viral diagnostic lab.'
  },
  {
    id: '18',
    name: 'Koidu Government Hospital',
    location: 'Hospital Road, Koidu Town',
    district: 'Kono',
    phone: '+232 76 333444',
    type: 'Government District Hospital',
    is24Hour: true,
    isAddictionSupport: false,
    lat: 8.643,
    lng: -10.972,
    description: 'The main health center for the diamond-rich Kono district, supporting thousands of residents.'
  },
  {
    id: '29',
    name: 'Kono Pharmacy & Drugs',
    location: 'Koidu Central, Koidu',
    district: 'Kono',
    phone: '+232 76 444333',
    type: 'Pharmacy',
    is24Hour: false,
    isAddictionSupport: false,
    lat: 8.641,
    lng: -10.974,
    description: 'Major drug supplier in Koidu, providing affordable essential medicines.'
  },
  {
    id: '19',
    name: 'Kailahun Government Hospital',
    location: 'Kailahun Town',
    district: 'Kailahun',
    phone: '+232 76 777888',
    type: 'Government District Hospital',
    is24Hour: true,
    isAddictionSupport: false,
    lat: 8.276,
    lng: -10.573,
    description: 'Strategic hospital in the far east, crucial for maternal health and malaria control.'
  },
  {
    id: '30',
    name: 'Nixon Memorial Hospital',
    location: 'Segbwema, Kailahun',
    district: 'Kailahun',
    phone: '+232 78 555111',
    type: 'Mission Hospital',
    is24Hour: true,
    isAddictionSupport: false,
    lat: 7.994,
    lng: -10.947,
    description: 'Long-standing mission hospital providing surgery and specialized pediatric care in Segbwema.'
  },
  {
    id: '46',
    name: 'Pendembu Community Health Centre',
    location: 'Pendembu Town',
    district: 'Kailahun',
    phone: '+232 76 777000',
    type: 'Government Health Facility',
    is24Hour: true,
    isAddictionSupport: false,
    lat: 8.112,
    lng: -10.712,
    description: 'Major primary health hub for the trading community of Pendembu.'
  },
  {
    id: '47',
    name: 'Daru Military Hospital',
    location: 'Daru Town',
    district: 'Kailahun',
    phone: '+232 76 888111',
    type: 'Military Hospital',
    is24Hour: true,
    isAddictionSupport: false,
    lat: 7.992,
    lng: -10.842,
    description: 'Provides surgical and general medical support to personnel and the local population.'
  },
  {
    id: '48',
    name: 'Koindu Community Health Centre',
    location: 'Koindu Town',
    district: 'Kailahun',
    phone: '+232 76 999222',
    type: 'Government Health Facility',
    is24Hour: true,
    isAddictionSupport: false,
    lat: 8.431,
    lng: -10.323,
    description: 'Vital border health post serving Kailahun North and cross-border trade travelers.'
  },
  {
    id: '49',
    name: 'Kailahun City Pharmacy',
    location: 'Kailahun Central',
    district: 'Kailahun',
    phone: '+232 76 123987',
    type: 'Pharmacy',
    is24Hour: false,
    isAddictionSupport: false,
    lat: 8.275,
    lng: -10.575,
    description: 'Leading retail pharmacy in the heart of Kailahun Town.'
  },

  // SOUTHERN PROVINCE (Bo, Moyamba, Pujehun, Bonthe)
  {
    id: '4',
    name: 'Bo Government Hospital',
    location: 'Hospital Road, Bo',
    district: 'Bo',
    phone: '+232 32 240201',
    type: 'Government Regional Hospital',
    is24Hour: true,
    isAddictionSupport: false,
    lat: 7.954,
    lng: -11.738,
    description: 'The second largest hospital in the country, serving as the southern regional hub.'
  },
  {
    id: '31',
    name: 'Bo Central Pharmacy',
    location: 'Fenton Road, Bo',
    district: 'Bo',
    phone: '+232 32 222111',
    type: 'Pharmacy',
    is24Hour: false,
    isAddictionSupport: false,
    lat: 7.956,
    lng: -11.741,
    description: 'Providing pharmaceutical services and medical supplies for the city of Bo.'
  },
  {
    id: '20',
    name: 'Moyamba Government Hospital',
    location: 'Moyamba Town',
    district: 'Moyamba',
    phone: '+232 76 222333',
    type: 'Government District Hospital',
    is24Hour: true,
    isAddictionSupport: false,
    lat: 8.158,
    lng: -12.432,
    description: 'Primary medical facility for the Moyamba district, offering outpatient and emergency services.'
  },
  {
    id: '21',
    name: 'Pujehun District Hospital',
    location: 'Pujehun Town',
    district: 'Pujehun',
    phone: '+232 76 999000',
    type: 'Government District Hospital',
    is24Hour: true,
    isAddictionSupport: false,
    lat: 7.352,
    lng: -11.719,
    description: 'Key facility in the south, essential for regional healthcare and pediatric support.'
  },
  {
    id: '40',
    name: 'Zimmi Community Health Centre',
    location: 'Zimmi Town',
    district: 'Pujehun',
    phone: '+232 76 111444',
    type: 'Government Health Facility',
    is24Hour: true,
    isAddictionSupport: false,
    lat: 7.031,
    lng: -11.308,
    description: 'Important border town facility serving deep Southern Pujehun.'
  },
  {
    id: '41',
    name: 'Potoru Community Health Centre',
    location: 'Potoru',
    district: 'Pujehun',
    phone: '+232 76 222555',
    type: 'Government Health Facility',
    is24Hour: true,
    isAddictionSupport: false,
    lat: 7.234,
    lng: -11.512,
    description: 'Primary care facility for the Potoru chiefdom area.'
  },
  {
    id: '42',
    name: 'Pujehun Central Pharmacy',
    location: 'Pujehun Town',
    district: 'Pujehun',
    phone: '+232 76 333666',
    type: 'Pharmacy',
    is24Hour: false,
    isAddictionSupport: false,
    lat: 7.350,
    lng: -11.721,
    description: 'Full-service pharmacy located in the Pujehun town center.'
  },
  {
    id: '22',
    name: 'Bonthe Government Hospital',
    location: 'Bonthe Island',
    district: 'Bonthe',
    phone: '+232 76 888999',
    type: 'Government District Hospital',
    is24Hour: true,
    isAddictionSupport: false,
    lat: 7.525,
    lng: -12.505,
    description: 'Serving the island community of Bonthe and neighboring riverine areas.'
  },
  {
    id: '32',
    name: 'Mattru Jong Hospital',
    location: 'Mattru Jong',
    district: 'Bonthe',
    phone: '+232 76 111333',
    type: 'Government District Hospital',
    is24Hour: true,
    isAddictionSupport: false,
    lat: 7.625,
    lng: -12.125,
    description: 'Serving the mainland part of Bonthe district with general surgery and maternal health.'
  },
  {
    id: '43',
    name: 'York Island Clinic',
    location: 'York Island',
    district: 'Bonthe',
    phone: '+232 76 444777',
    type: 'Government Health Facility',
    is24Hour: true,
    isAddictionSupport: false,
    lat: 7.545,
    lng: -12.470,
    description: 'Essential health post for the historic York Island community.'
  },
  {
    id: '44',
    name: 'Tihun Health Centre',
    location: 'Tihun Town',
    district: 'Bonthe',
    phone: '+232 76 555888',
    type: 'Government Health Facility',
    is24Hour: true,
    isAddictionSupport: false,
    lat: 7.612,
    lng: -12.285,
    description: 'Mainland health centre providing primary care for Sogbini chiefdom.'
  },
  {
    id: '45',
    name: 'Mattru Jong Pharmacy',
    location: 'Mattru Jong Central',
    district: 'Bonthe',
    phone: '+232 76 666999',
    type: 'Pharmacy',
    is24Hour: false,
    isAddictionSupport: false,
    lat: 7.624,
    lng: -12.127,
    description: 'Primary source of medical supplies in the Mattru Jong town area.'
  },

  {
    id: '33',
    name: 'Karene Health Centre',
    location: 'Karene Town',
    district: 'Karene',
    phone: '+232 77 444333',
    type: 'Government Health Facility',
    is24Hour: true,
    isAddictionSupport: false,
    lat: 9.355,
    lng: -12.332,
    description: 'New healthcare hub serving the recently created Karene district.'
  },
  {
    id: '34',
    name: 'Falaba District Clinic',
    location: 'Falaba Town',
    district: 'Falaba',
    phone: '+232 76 000222',
    type: 'Government Health Facility',
    is24Hour: true,
    isAddictionSupport: false,
    lat: 9.852,
    lng: -11.233,
    description: 'Remote facility providing vital primary healthcare for residents near the northern border.'
  }
];
